const express = require("express");
const bcrypt = require("bcryptjs");
const { requireAuth, requireMaster } = require("../middleware/auth");
const { createEventLog } = require("../utils/eventLog");
const { getConfig, validateConfig, syncProdToQa } = require("../services/syncProdToQa");
const Alliance = require("../models/alliance");
const Account = require("../models/account");
const Player = require("../models/player");
const PlayerPowerHistory = require("../models/playerPowerHistory");
const { EventLog } = require("../models/eventLog");
const { normalizeAllianceCode, normalizeServerNumber, isValidAllianceCode, isValidServerNumber } = require("../utils/tenant");
const router = express.Router();
function statusKey(resultOrKey) { const key = typeof resultOrKey === "string" ? resultOrKey : resultOrKey?.error; return key || "sync_failed"; }
function pinOk(v){ return /^\d{6}$/.test(String(v||"").trim()); }
async function nextAllianceId(){ const last=await Alliance.findOne({}).sort({allianceId:-1}).lean(); return (last?.allianceId||0)+1; }
function username(code, server, role){ return `${normalizeAllianceCode(code)}#${server}:${role === "alliance_admin" ? "admin" : role}`; }
async function upsertAllianceAccounts(alliance, adminPin, supervisorPin){ const specs=[{role:"alliance_admin",pin:adminPin},{role:"supervisor",pin:supervisorPin}]; for(const spec of specs){ if(!spec.pin) continue; const pinHash=await bcrypt.hash(String(spec.pin),10); await Account.updateOne({username:username(alliance.code,alliance.serverNumber,spec.role)},{$set:{allianceId:alliance.allianceId,role:spec.role,pinHash,isActive:true}}, {upsert:true}); } }
router.get("/", requireAuth, requireMaster, (req, res) => { const config = getConfig(); res.render("admin/index", { user: req.user, syncEnabled: config.enabled, syncConfigError: validateConfig(config), syncMessage: req.query.syncMessage || "", syncStatus: req.query.syncStatus || "" }); });
router.get("/alliances", requireAuth, requireMaster, async (req,res)=>{ const alliances=await Alliance.find({}).sort({allianceId:1}).lean(); res.render("admin/alliances",{user:req.user,alliances,message:req.query.message||"",error:req.query.error||"",credentials:null}); });
router.post("/alliances", requireAuth, requireMaster, async (req,res)=>{ const t=res.locals.t||((k)=>k); const code=normalizeAllianceCode(req.body.code); const serverNumber=normalizeServerNumber(req.body.serverNumber); const adminPin=String(req.body.adminPin||"").trim(); const supervisorPin=String(req.body.supervisorPin||"").trim(); const displayName=String(req.body.displayName||"").trim()||code; if(!isValidAllianceCode(code)||!isValidServerNumber(serverNumber)||!pinOk(adminPin)||!pinOk(supervisorPin)) return res.redirect(`/admin/alliances?error=${encodeURIComponent(t("err_invalid_input") || "Dati non validi")}`); const exists=await Alliance.findOne({codeNormalized:code,serverNumber}).lean(); if(exists) return res.redirect(`/admin/alliances?error=${encodeURIComponent(t("alliance_exists"))}`); const alliance=await Alliance.create({allianceId:await nextAllianceId(),code,codeNormalized:code,serverNumber,displayName,isActive:true}); await upsertAllianceAccounts(alliance,adminPin,supervisorPin); await createEventLog(req,"alliance_create",`allianceId=${alliance.allianceId}`); return res.redirect(`/admin/alliances?message=${encodeURIComponent(`${t("alliance_created")}. ${t("credentials_to_share")}: ${code}/${serverNumber} admin ${adminPin}, supervisor ${supervisorPin}`)}`); });
router.post("/alliances/:id/deactivate", requireAuth, requireMaster, async (req,res)=>{ const t=res.locals.t||((k)=>k); const allianceId=Number(req.params.id); await Alliance.updateOne({allianceId},{$set:{isActive:false}}); await createEventLog(req,"alliance_deactivate",`allianceId=${allianceId}`); res.redirect(`/admin/alliances?message=${encodeURIComponent(t("alliance_deactivated"))}`); });
router.post("/alliances/:id/update-pins", requireAuth, requireMaster, async (req,res)=>{ const t=res.locals.t||((k)=>k); const alliance=await Alliance.findOne({allianceId:Number(req.params.id)}).lean(); if(!alliance) return res.redirect(`/admin/alliances?error=Not found`); const adminPin=pinOk(req.body.adminPin)?String(req.body.adminPin).trim():null; const supervisorPin=pinOk(req.body.supervisorPin)?String(req.body.supervisorPin).trim():null; if(!adminPin&&!supervisorPin) return res.redirect(`/admin/alliances?error=${encodeURIComponent(t("err_invalid_input") || "PIN non validi")}`); await upsertAllianceAccounts(alliance,adminPin,supervisorPin); res.redirect(`/admin/alliances?message=${encodeURIComponent(t("update_pin"))}`); });
router.post("/alliances/:id/delete", requireAuth, requireMaster, async (req,res)=>{ const t=res.locals.t||((k)=>k); const allianceId=Number(req.params.id); const linked=await Promise.all([Player.exists({allianceId}),PlayerPowerHistory.exists({allianceId}),EventLog.exists({allianceId})]); if(linked.some(Boolean)) return res.redirect(`/admin/alliances?error=${encodeURIComponent(t("cannot_delete_linked_alliance"))}`); await Alliance.deleteOne({allianceId}); await Account.deleteMany({allianceId}); res.redirect(`/admin/alliances?message=${encodeURIComponent(t("delete_alliance"))}`); });
router.post("/sync-prod-to-qa", requireAuth, requireMaster, async (req, res) => { const t = res.locals.t || ((key) => key); const confirmation = String(req.body.confirmation || "").trim(); if (confirmation !== "ALLINEA QA") return res.redirect(`/admin?syncStatus=error&syncMessage=${encodeURIComponent(t("sync_confirmation_required"))}`); const validationError = validateConfig(); if (validationError) { await createEventLog(req, "sync_prod_to_qa", `userLevel=${req.user.authLevel}|success=false|error=${validationError}`); return res.redirect(`/admin?syncStatus=error&syncMessage=${encodeURIComponent(t(statusKey(validationError)))}`); } const result = await syncProdToQa(); const details = [`userLevel=${req.user.authLevel}`,`success=${result.success}`,`collections=${result.collections.join(",")}`,`totalDocuments=${result.totalDocuments}`,`documentsByCollection=${JSON.stringify(result.documentsByCollection)}`,result.error ? `error=${result.error}` : "error="].join("|"); await createEventLog(req, "sync_prod_to_qa", details); const messageKey = result.success ? "sync_success" : statusKey(result); return res.redirect(`/admin?syncStatus=${result.success ? "success" : "error"}&syncMessage=${encodeURIComponent(t(messageKey))}`); });
module.exports = router;
